server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_system
    username: postgres
    password: admin
    hikari:
      maximumPoolSize: 15
  jpa:
    hibernate:
      ddl-auto: none
    show_sql: true
    format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
